default_context:
  author_name: "Roberto Vera Alvarez"
  user_email: "veraalva@ncbi.nlm.nih.gov"
  project_name: "pm4ngs-chipexo"
  dataset_name: "PRJNA338159"
  is_data_in_SRA: "y"
  sequencing_technology: "single-end"
  create_demo: "n"
  number_spots: "1000000"
  organism: "Escherichia coli"
  genome_name: "NC_000913.3"
  genome_dir: "{{ cookiecutter.genome_name}}"
  aligner_index_dir: "{{ cookiecutter.genome_dir}}/BWA/"
  genome_fasta: "{{ cookiecutter.genome_dir}}/NC_000913.3.fa"
  genome_gtf: "{{ cookiecutter.genome_dir}}/NC_000913.3.gtf"
  genome_chromsizes: "{{ cookiecutter.genome_dir}}/NC_000913.3.sizes"
  use_docker: "y"
  max_number_threads: "32"